language: python
python:
  - "2.7"
  - "3.3"
before_install:
  # pytest-qt
  - sudo apt-get install -qq python-pyside
  #- export PYTHONPATH="$PYTHONPATH:/usr/lib/python2.7/dist-packages/"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  
install:
  - pip uninstall -y pytest
  - pip install -r requirements.txt
env:
  - PYTEST_VERSION=2.3.5 PLUGS_SITE=http://pytest-plugs.herokuapp.com
  - PYTEST_VERSION=2.4.2 PLUGS_SITE=http://pytest-plugs.herokuapp.com
  - PYTEST_VERSION=2.5.2 PLUGS_SITE=http://pytest-plugs.herokuapp.com
script: 
  - python run.py
