language: python
python:
  - "2.7"
  - "3.4"

# for plugins that require UI
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

install:
  - pip uninstall -y pytest
  - pip install -r requirements.txt
env:
  - PYTEST_VERSION=2.5.2 PLUGS_SITE=http://pytest-plugs.herokuapp.com
  - PYTEST_VERSION=2.6.2 PLUGS_SITE=http://pytest-plugs.herokuapp.com
script: 
  - python run.py

branches:
  only:
    - master
    - /feature-.*/
  
