language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
install:
  - pip uninstall -y pytest
  - pip install --use-mirrors pytest==$PYTEST_VERSION
  - pip install --use-mirrors tox
  - pip install --use-mirrors simplejson
env:
  - PYTEST_VERSION=2.3.5
  - PYTEST_VERSION=2.4.2  
script: 
  - python run.py
