language: python
python:
  - "2.7"
  - "3.3"

# for plugins that require UI
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

install:
  # pytest-qt setup (from https://github.com/nicoddemus/pytest-qt/blob/master/.travis.yml)
  # don't install PySide from pip otherwise it will try to compile the whole
  # thing and travis will time out the job
  - sudo apt-get install -qq python-pyside
  - ln -s /usr/lib/python$TRAVIS_PYTHON_VERSION/dist-packages/PySide /home/travis/virtualenv/python$TRAVIS_PYTHON_VERSION/lib/python$TRAVIS_PYTHON_VERSION/site-packages/PySide -v

  # uninstall default travis pytest and install normal requirements
  - pip uninstall -y pytest
  - pip install -r requirements.txt
env:
  - PYTEST_VERSION=2.3.5 PLUGS_SITE=http://pytest-plugs.herokuapp.com
  - PYTEST_VERSION=2.4.2 PLUGS_SITE=http://pytest-plugs.herokuapp.com
  - PYTEST_VERSION=2.5.2 PLUGS_SITE=http://pytest-plugs.herokuapp.com
script: 
  - python run.py

branches:
  only:
    - master
    - /feature-.*/
  
