language: python
python:
  - "2.6"
  - "2.7"
install:
  - pip install tox
  - pip install pytest==$PYTEST_VERSION
  - pip install simplejson
env:
  - PYTEST_VERSION=2.3.5
  - PYTEST_VERSION=2.4.2  
script: 
  - python run.py
